browserprofile.global.headless = true
browserprofile.global.acceptInsecureCertificates = true

# A local Chrome with a small window size
browserprofile.Chrome_1024x768.name = Chrome 1024x768
browserprofile.Chrome_1024x768.browser = chrome
browserprofile.Chrome_1024x768.browserResolution = 1024x768
browserprofile.Chrome_1024x768.arguments = --ignore-certificate-errors
browserprofile.Chrome_1024x768.headless = true

# Local Chrome but with larger window size
browserprofile.Chrome_1500x1000.name = Chrome 1500x1000
browserprofile.Chrome_1500x1000.browser = chrome
browserprofile.Chrome_1500x1000.browserResolution = 1500x1200
browserprofile.Chrome_1500x1000.arguments = --ignore-certificate-errors
browserprofile.Chrome_1500x1000.headless = true

# Firefox
browserprofile.FF_1024x768.name = Firefox 1024x768
browserprofile.FF_1024x768.browser = firefox
browserprofile.FF_1024x768.browserResolution = 1024x768
browserprofile.FF_1024x768.headless = true
