/*
 * GNU Affero General Public License (AGPLv3)
 *
 * Copyright (c) 2026 Xceptance
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package com.xceptance.neodymium.ai.generator;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import com.xceptance.neodymium.ai.core.LlmClient;

/**
 * A deterministic AI agent that reactively heals broken ASSERT validations generated by the creative generator.
 * Analyzes the SUT page's visual/structural state via the simplified DOM context and dynamically resolves alternatives.
 *
 * @author AI-generated: Gemini 2.5 Flash
 * @author Xceptance GmbH 2026
 */
public final class ValidationAgent
{
    private static final Logger LOG = LoggerFactory.getLogger(ValidationAgent.class);

    private final LlmClient llmClient;

    /**
     * Constructs a new ValidationAgent with the specified LLM client.
     *
     * @param llmClient the LlmClient utilized for sending prompts and resolving healed validations
     */
    public ValidationAgent(final LlmClient llmClient)
    {
        this.llmClient = llmClient;
    }

    /**
     * Reactively heals a broken ASSERT description by checking the current DOM context 
     * using the deterministic executing LLM temperature.
     * 
     * @param failedDescription the original assertion description that threw an exception
     * @param errorMessage      the execution/exception error message encountered
     * @param domContext        the current simplified DOM representation of the page
     * @return a healed, working assertion description, or {@code null} if healing failed or was aborted
     */
    public String healValidation(final String failedDescription, final String errorMessage, final String domContext)
    {
        // Define the instruction set for the LLM validating structural properties in DOM context.
        final String systemPrompt = """
            You are a strict, deterministic Validation Healing Agent.
            A generative AI attempted to validate part of a web page using an ASSERT action, but it failed execution.
            Your job is to look at the DOM context and provide a robust, working alternative validation description.
            
            RULES:
            1. ONLY check for functionally or structurally important text that actually exists in the DOM.
            2. Never use structural terms like "heading", "headline", or "button layout". Just refer to the text directly (e.g. "Validate the text 'X' is visible").
            3. Do NOT wrap full sentences in quotes. Only quote specific text snippets.
            4. If the intended text genuinely does not exist or isn't functionally relevant to the failed validation's goal, return EXACTLY the word: ABORT.
            5. Otherwise, return ONLY the raw string for the new action description. No explanation, no JSON, no formatting.
            """;
            
        // Build the contextual user prompt including the failing description, the error message, and DOM context.
        final String userPrompt = "The following validation failed execution: '" + failedDescription + "'\n" +
                            "Error: " + errorMessage + "\n\n" +
                            "Here is the current simplified DOM:\n" + domContext + "\n\n" +
                            "Please provide a strong, working alternative validation description following the rules, or 'ABORT'.";

        try
        {
            // Execute the chat interaction with the LLM.
            final String response = llmClient.chat(systemPrompt, userPrompt);
            if (response == null || response.trim().isEmpty())
            {
                return null;
            }
            
            final String trimmedResponse = response.trim();
            // If the model determined the validation cannot be saved, it returns ABORT.
            if ("ABORT".equalsIgnoreCase(trimmedResponse))
            {
                return null;
            }
            return trimmedResponse;
        }
        catch (final Exception e)
        {
            LOG.warn("ValidationAgent failed to heal validation: {}", e.getMessage());
            return null;
        }
    }
}
