/*
 * MIT License
 *
 * Copyright (c) 2026 Xceptance
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package com.xceptance.neodymium.ai.generator;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.xceptance.neodymium.ai.core.LlmClient;

/**
 * A deterministic AI agent that reactively heals broken ASSERT validations generated by the creative generator.
  *
 * // AI-generated: Gemini 2.0 Flash
*/
public class ValidationAgent {
    private static final Logger LOG = LoggerFactory.getLogger(ValidationAgent.class);
    private final LlmClient llmClient;

    public ValidationAgent(LlmClient llmClient) {
        this.llmClient = llmClient;
    }

    /**
     * Reactively heals a broken ASSERT description by checking the current DOM context 
     * using the deterministic executing LLM temperature.
     * 
     * @param failedDescription The description that threw an exception.
     * @param errorMessage The exception message.
     * @param domContext The current simplified DOM.
     * @return A healed action description, or null if it cannot be healed.
     */
    public String healValidation(String failedDescription, String errorMessage, String domContext) {
        String systemPrompt = """
            You are a strict, deterministic Validation Healing Agent.
            A generative AI attempted to validate part of a web page using an ASSERT action, but it failed execution.
            Your job is to look at the DOM context and provide a robust, working alternative validation description.
            
            RULES:
            1. ONLY check for functionally or structurally important text that actually exists in the DOM.
            2. Never use structural terms like "heading", "headline", or "button layout". Just refer to the text directly (e.g. "Validate the text 'X' is visible").
            3. Do NOT wrap full sentences in quotes. Only quote specific text snippets.
            4. If the intended text genuinely does not exist or isn't functionally relevant to the failed validation's goal, return EXACTLY the word: ABORT.
            5. Otherwise, return ONLY the raw string for the new action description. No explanation, no JSON, no formatting.
            """;
            
        String userPrompt = "The following validation failed execution: '" + failedDescription + "'\n" +
                            "Error: " + errorMessage + "\n\n" +
                            "Here is the current simplified DOM:\n" + domContext + "\n\n" +
                            "Please provide a strong, working alternative validation description following the rules, or 'ABORT'.";

        try {
            String response = llmClient.chat(systemPrompt, userPrompt);
            if (response == null || response.trim().isEmpty()) {
                return null;
            }
            response = response.trim();
            if ("ABORT".equalsIgnoreCase(response)) {
                return null;
            }
            return response;
        } catch (Exception e) {
            LOG.warn("ValidationAgent failed to heal validation: {}", e.getMessage());
            return null;
        }
    }
}
