/*
 * GNU Affero General Public License (AGPLv3)
 *
 * Copyright (c) 2026 Xceptance
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package org.neodymium.ai.action;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Represents a single locator candidate generated by the LLM during action extraction.
 * Captures the target selector string, strategy label, stability score, and reasoning.
 *
 * @author AI-generated: Gemini 3.6 Flash
 * @author Xceptance GmbH 2026
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class LocatorCandidate
{
    private final String locator;
    private final String strategy;
    private final double score;
    private final String reasoning;

    /**
     * Constructs a default empty LocatorCandidate.
     */
    public LocatorCandidate()
    {
        this("", "UNKNOWN", 0.0, "");
    }

    /**
     * JsonCreator constructor for Jackson deserialization.
     *
     * @param locator   the target CSS selector or locator string
     * @param strategy  the selection strategy (e.g. ID, ATTRIBUTE, CLASS, ACCESSIBILITY, DATA_AI)
     * @param score     the estimated stability confidence score (0.0 to 1.0)
     * @param reasoning brief rationale for this candidate choice
     */
    @JsonCreator
    public LocatorCandidate(
            @JsonProperty("locator") final String locator,
            @JsonProperty("strategy") final String strategy,
            @JsonProperty("score") final Double score,
            @JsonProperty("reasoning") final String reasoning)
    {
        this.locator = locator != null ? locator.trim() : "";
        this.strategy = strategy != null ? strategy.trim() : "UNKNOWN";
        this.score = score != null ? score : 0.0;
        this.reasoning = reasoning != null ? reasoning.trim() : "";
    }

    /**
     * Convenience constructor for locator string and score.
     *
     * @param locator the target locator string
     * @param score   the candidate score
     */
    public LocatorCandidate(final String locator, final double score)
    {
        this(locator, "UNKNOWN", score, "");
    }

    public String getLocator()
    {
        return locator;
    }

    public String getStrategy()
    {
        return strategy;
    }

    public double getScore()
    {
        return score;
    }

    public String getReasoning()
    {
        return reasoning;
    }

    @Override
    public boolean equals(final Object o)
    {
        if (this == o)
        {
            return true;
        }
        if (o == null || getClass() != o.getClass())
        {
            return false;
        }
        final LocatorCandidate candidate = (LocatorCandidate) o;
        return Double.compare(candidate.score, score) == 0 &&
                Objects.equals(locator, candidate.locator) &&
                Objects.equals(strategy, candidate.strategy) &&
                Objects.equals(reasoning, candidate.reasoning);
    }

    @Override
    public int hashCode()
    {
        return Objects.hash(locator, strategy, score, reasoning);
    }

    @Override
    public String toString()
    {
        return "LocatorCandidate{" +
                "locator='" + locator + '\'' +
                ", strategy='" + strategy + '\'' +
                ", score=" + score +
                ", reasoning='" + reasoning + '\'' +
                '}';
    }
}
