/*
 * GNU Affero General Public License (AGPLv3)
 *
 * Copyright (c) 2026 Xceptance
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package org.neodymium.ai.util;

import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Utility class for sanitizing CSS selector strings generated by AI/LLM providers,
 * escaping special characters in class name identifiers (such as decimal dots, fractional slashes,
 * state variant colons, and arbitrary brackets) while preserving valid W3C CSS pseudo-classes.
 *
 * @author AI-generated: Gemini 3.5 Flash
 * @author Xceptance GmbH 2026
 */
public final class CssSelectorSanitizer
{
    private static final Pattern FRACTIONAL_SLASHES_PATTERN = Pattern.compile("(\\.[a-zA-Z0-9_\\-]+)/(\\d+)");
    private static final Pattern DECIMAL_DOTS_PATTERN = Pattern.compile("(\\.[a-zA-Z0-9_\\-/]+)\\.(\\d+)");
    private static final Pattern TAILWIND_VARIANTS_PATTERN = Pattern.compile("(\\.(?:sm|md|lg|xl|2xl|hover|focus|active|dark|group-hover|peer-focus|disabled)):([a-zA-Z0-9_\\-\\[\\]\\#]+)");
    private static final Pattern ARBITRARY_BRACKETS_PATTERN = Pattern.compile("(\\.[a-zA-Z0-9_:#-]+)\\[([^\\]]+)\\]");

    private CssSelectorSanitizer()
    {
        // Private constructor for utility class
    }

    /**
     * Sanitizes raw CSS selector strings generated by LLMs by escaping invalid unescaped characters in class names,
     * such as decimal points in Tailwind classes (e.g. {@code py-0.5} -&gt; {@code py-0\.5}),
     * fractional slashes (e.g. {@code w-1/2} -&gt; {@code w-1\/2}), state variants (e.g. {@code hover:bg-slate} -&gt; {@code hover\:bg-slate}),
     * and arbitrary values (e.g. {@code top-[10px]} -&gt; {@code top-\[10px\]}), while leaving standard W3C CSS pseudo-classes intact.
     *
     * @param selector the raw CSS selector string
     * @return the sanitized, valid CSS selector string
     */
    public static String sanitize(final String selector)
    {
        if (selector == null || selector.isBlank())
        {
            return selector;
        }

        String sanitized = selector;

        // 1. Escape slashes in fractional Tailwind class names (e.g. .w-1/2 -> .w-1\/2, .h-3/4 -> .h-3\/4)
        sanitized = FRACTIONAL_SLASHES_PATTERN.matcher(sanitized).replaceAll("$1\\\\/$2");

        // 2. Escape decimal dots inside class tokens (e.g. .py-0.5 -> .py-0\.5, .p-2.5 -> .p-2\.5)
        sanitized = DECIMAL_DOTS_PATTERN.matcher(sanitized).replaceAll("$1\\\\.$2");

        // 3. Escape Tailwind state variant colons (e.g. .sm:flex -> .sm\:flex, .hover:bg-blue -> .hover\:bg-blue)
        sanitized = TAILWIND_VARIANTS_PATTERN.matcher(sanitized).replaceAll("$1\\\\:$2");

        // 4. Escape brackets and hashes in Tailwind arbitrary values (e.g. .top-[10px] -> .top-\[10px\], .bg-[#f0f0f0] -> .bg-\[\#f0f0f0\])
        sanitized = ARBITRARY_BRACKETS_PATTERN.matcher(sanitized).replaceAll(matcher ->
        {
            final String prefix = matcher.group(1);
            final String inner = matcher.group(2).replace("#", "\\#");
            return Matcher.quoteReplacement(prefix + "\\[" + inner + "\\]");
        });

        return sanitized;
    }
}
