/*
 * GNU Affero General Public License (AGPLv3)
 *
 * Copyright (c) 2026 Xceptance
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package org.neodymium.ai.util;

import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Utility class for sanitizing CSS selector strings generated by AI/LLM providers,
 * escaping special characters in class name identifiers (such as decimal dots, fractional slashes,
 * state variant colons, and arbitrary brackets) while preserving valid W3C CSS pseudo-classes
 * and attribute presence selectors.
 *
 * @author AI-generated: Gemini 3.5 Flash
 * @author Xceptance GmbH 2026
 */
public final class CssSelectorSanitizer
{
    private static final Pattern FRACTIONAL_SLASHES_PATTERN = Pattern.compile("(\\.[a-zA-Z0-9_\\-]+)/(\\d+)");
    private static final Pattern DECIMAL_DOTS_PATTERN = Pattern.compile("(\\.[a-zA-Z0-9_\\-/]+)\\.(\\d+)");
    private static final Pattern TAILWIND_VARIANTS_PATTERN = Pattern.compile("(\\.(?:sm|md|lg|xl|2xl|hover|focus|active|dark|group-hover|peer-focus|disabled)):([a-zA-Z0-9_\\-\\[\\]\\#]+)");
    private static final Pattern ARBITRARY_BRACKETS_PATTERN = Pattern.compile("(\\.[a-zA-Z0-9_:#-]*-[a-zA-Z0-9_:#-]*)\\[([^\\]]+)\\]");

    /**
     * Standard W3C CSS pseudo-classes that must never have their colons escaped when preceded by a class name.
     */
    private static final Set<String> CSS_PSEUDO_CLASSES = Set.of(
        "hover", "focus", "focus-within", "focus-visible", "active", "disabled", "enabled",
        "checked", "unchecked", "indeterminate", "required", "optional", "valid", "invalid",
        "user-valid", "user-invalid", "in-range", "out-of-range", "read-only", "read-write",
        "default", "blank", "empty", "first-child", "last-child", "only-child",
        "first-of-type", "last-of-type", "only-of-type", "nth-child", "nth-last-child",
        "nth-of-type", "nth-last-of-type", "root", "target", "visited", "link", "any-link",
        "not", "is", "where", "has", "before", "after", "first-letter", "first-line",
        "placeholder", "marker", "selection", "backdrop"
    );

    /**
     * Common HTML/SVG attribute presence names that must never be escaped as Tailwind arbitrary values.
     */
    private static final Set<String> KNOWN_ATTRIBUTES = Set.of(
        "required", "disabled", "readonly", "checked", "multiple", "autofocus", "hidden",
        "selected", "href", "src", "alt", "title", "type", "name", "id", "class",
        "value", "placeholder", "aria-label", "aria-hidden", "data-testid", "data-ai"
    );

    private CssSelectorSanitizer()
    {
        // Private constructor for utility class
    }

    /**
     * Sanitizes raw CSS selector strings generated by LLMs by escaping invalid unescaped characters in class names,
     * such as decimal points in Tailwind classes (e.g. {@code py-0.5} -&gt; {@code py-0\.5}),
     * fractional slashes (e.g. {@code w-1/2} -&gt; {@code w-1\/2}), state variants (e.g. {@code hover:bg-slate} -&gt; {@code hover\:bg-slate}),
     * and arbitrary values (e.g. {@code top-[10px]} -&gt; {@code top-\[10px\]}), while leaving standard W3C CSS pseudo-classes
     * and attribute presence selectors intact.
     *
     * @param selector the raw CSS selector string
     * @return the sanitized, valid CSS selector string
     */
    public static String sanitize(final String selector)
    {
        if (selector == null || selector.isBlank())
        {
            return selector;
        }

        String sanitized = selector;

        // 1. Escape slashes in fractional Tailwind class names (e.g. .w-1/2 -> .w-1\/2, .h-3/4 -> .h-3\/4)
        sanitized = FRACTIONAL_SLASHES_PATTERN.matcher(sanitized).replaceAll("$1\\\\/$2");

        // 2. Escape decimal dots inside class tokens (e.g. .py-0.5 -> .py-0\.5, .p-2.5 -> .p-2\.5)
        sanitized = DECIMAL_DOTS_PATTERN.matcher(sanitized).replaceAll("$1\\\\.$2");

        // 3. Escape Tailwind state variant colons (e.g. .sm:flex -> .sm\:flex, .hover:bg-blue -> .hover\:bg-blue)
        // while preserving standard CSS pseudo-classes on state classes (e.g. .active:hover -> .active:hover, .disabled:focus -> .disabled:focus)
        sanitized = TAILWIND_VARIANTS_PATTERN.matcher(sanitized).replaceAll(matcher ->
        {
            final String prefix = matcher.group(1);
            final String suffix = matcher.group(2);
            if (CSS_PSEUDO_CLASSES.contains(suffix.toLowerCase()))
            {
                return Matcher.quoteReplacement(prefix + ":" + suffix);
            }
            return Matcher.quoteReplacement(prefix + "\\:" + suffix);
        });

        // 4. Escape brackets and hashes in Tailwind arbitrary values (e.g. .top-[10px] -> .top-\[10px\], .bg-[#f0f0f0] -> .bg-\[\#f0f0f0\])
        // Standard CSS attribute selectors contain '=' or valid attribute presence names (e.g. .form-control[required], .btn[disabled])
        // and must NOT have their brackets escaped.
        sanitized = ARBITRARY_BRACKETS_PATTERN.matcher(sanitized).replaceAll(matcher ->
        {
            final String prefix = matcher.group(1);
            final String inner = matcher.group(2);

            // Attribute selectors containing comparison operators (=, ~=, |=, ^=, $=, *=)
            if (inner.contains("=") || inner.contains("~") || inner.contains("|") || inner.contains("^") || inner.contains("$") || inner.contains("*"))
            {
                return Matcher.quoteReplacement(prefix + "[" + inner + "]");
            }

            // Standard attribute presence selectors (e.g., [required], [disabled], [href])
            final String trimmedInner = inner.trim().toLowerCase();
            if (KNOWN_ATTRIBUTES.contains(trimmedInner) || isStandardAttributeIdentifier(trimmedInner))
            {
                return Matcher.quoteReplacement(prefix + "[" + inner + "]");
            }

            final String escapedInner = inner.replace("#", "\\#");
            return Matcher.quoteReplacement(prefix + "\\[" + escapedInner + "\\]");
        });

        return sanitized;
    }

    /**
     * Determines whether the given string represents a standard HTML/SVG attribute identifier.
     * Tailwind arbitrary values typically begin with numbers, colors (#), units, or CSS expressions.
     */
    private static boolean isStandardAttributeIdentifier(final String str)
    {
        if (str == null || str.isEmpty())
        {
            return false;
        }

        // Tailwind arbitrary values start with '#' (colors), digits, '-', or contain unit/calc indicators
        final char firstChar = str.charAt(0);
        if (firstChar == '#' || Character.isDigit(firstChar) || firstChar == '-' || firstChar == '.')
        {
            return false;
        }

        if (str.contains("px") || str.contains("rem") || str.contains("em") || str.contains("%")
            || str.contains("vh") || str.contains("vw") || str.contains("calc(") || str.contains("var(")
            || str.contains("rgb(") || str.contains("hsl(") || str.contains("_"))
        {
            return false;
        }

        return str.matches("^[a-zA-Z_:][a-zA-Z0-9_:-]*$");
    }
}
